//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGR.LEX.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LitigiosoEntities : DbContext
    {
        public LitigiosoEntities()
            : base("name=LitigiosoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TAnomalias> TAnomalias { get; set; }
        public virtual DbSet<TAsunto> TAsunto { get; set; }
        public virtual DbSet<TAudiencias> TAudiencias { get; set; }
        public virtual DbSet<TAudienciasDetalleExpediente> TAudienciasDetalleExpediente { get; set; }
        public virtual DbSet<TBitacoraNotificaciones> TBitacoraNotificaciones { get; set; }
        public virtual DbSet<TCircuitosJudiciales> TCircuitosJudiciales { get; set; }
        public virtual DbSet<TDespachosJudiciales> TDespachosJudiciales { get; set; }
        public virtual DbSet<TDetalleExpediente> TDetalleExpediente { get; set; }
        public virtual DbSet<TEstadoProcesal> TEstadoProcesal { get; set; }
        public virtual DbSet<TEstadosxAudiencia> TEstadosxAudiencia { get; set; }
        public virtual DbSet<TEstadosxExpediente> TEstadosxExpediente { get; set; }
        public virtual DbSet<TExpediente> TExpediente { get; set; }
        public virtual DbSet<TExpedientesAcumulados> TExpedientesAcumulados { get; set; }
        public virtual DbSet<TFormatosExpedientes> TFormatosExpedientes { get; set; }
        public virtual DbSet<TInstitucionesxExpediente> TInstitucionesxExpediente { get; set; }
        public virtual DbSet<TMateria> TMateria { get; set; }
        public virtual DbSet<TMediosNotificacion> TMediosNotificacion { get; set; }
        public virtual DbSet<TMoneda> TMoneda { get; set; }
        public virtual DbSet<TMovimientosxAudiencias> TMovimientosxAudiencias { get; set; }
        public virtual DbSet<TNegociacionesxExpediente> TNegociacionesxExpediente { get; set; }
        public virtual DbSet<TNotificacioneSinExpediente> TNotificacioneSinExpediente { get; set; }
        public virtual DbSet<TNotificacionesxExpediente> TNotificacionesxExpediente { get; set; }
        public virtual DbSet<TParticipacionEstado> TParticipacionEstado { get; set; }
        public virtual DbSet<TPlanosxExpediente> TPlanosxExpediente { get; set; }
        public virtual DbSet<TProcedenciaExpediente> TProcedenciaExpediente { get; set; }
        public virtual DbSet<TTerrenosAfectados> TTerrenosAfectados { get; set; }
        public virtual DbSet<TTerrenosxExpediente> TTerrenosxExpediente { get; set; }
        public virtual DbSet<TTipo> TTipo { get; set; }
        public virtual DbSet<TTipoAudiencia> TTipoAudiencia { get; set; }
        public virtual DbSet<TTipoExpediente> TTipoExpediente { get; set; }
        public virtual DbSet<TTipoGeneral> TTipoGeneral { get; set; }
        public virtual DbSet<TTiposNegociacion> TTiposNegociacion { get; set; }
        public virtual DbSet<TVotosxExpediente> TVotosxExpediente { get; set; }
        public virtual DbSet<TBitacoraMovimientos> TBitacoraMovimientos { get; set; }
        public virtual DbSet<TNatutalizaciones> TNatutalizaciones { get; set; }
        public virtual DbSet<TParametros> TParametros { get; set; }
    }
}
