//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGR.LEX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAudiencias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAudiencias()
        {
            this.TAudienciasDetalleExpediente = new HashSet<TAudienciasDetalleExpediente>();
            this.TMovimientosxAudiencias = new HashSet<TMovimientosxAudiencias>();
        }
    
        public int idAudiencia { get; set; }
        public int idTipoAudiencia { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime Hora { get; set; }
        public int idJuzgado { get; set; }
        public long Procurador { get; set; }
        public string Juez { get; set; }
    
        public virtual TTipoAudiencia TTipoAudiencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAudienciasDetalleExpediente> TAudienciasDetalleExpediente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMovimientosxAudiencias> TMovimientosxAudiencias { get; set; }
    }
}
