//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGR.LEX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBitacoraMovimientos
    {
        public int Id_Sistema { get; set; }
        public int Cedula_Usuario { get; set; }
        public System.DateTime Fecha_Movimiento { get; set; }
        public string Tabla { get; set; }
        public string Id_Llave { get; set; }
        public string Tipo_Movimiento { get; set; }
        public string Valores_Anteriores { get; set; }
        public string Valores_Actuales { get; set; }
    }
}
