//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGR.LEX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDetalleExpediente
    {
        public string idNumExpediente { get; set; }
        public bool AsignadoActual { get; set; }
        public long Procurador { get; set; }
        public int idMateria { get; set; }
        public int idTipo { get; set; }
        public int idAsunto { get; set; }
        public Nullable<int> idGeneral { get; set; }
        public Nullable<int> idParticipacion { get; set; }
        public int idEstadoProcesal { get; set; }
        public bool Inestimable { get; set; }
        public bool Activo { get; set; }
        public Nullable<System.DateTime> fechaFenecido { get; set; }
        public int Area { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> IdMonedaPretencion { get; set; }
        public decimal Pretension { get; set; }
        public Nullable<int> IdMonedaCuantia { get; set; }
        public decimal Cuantia { get; set; }
        public decimal Costas { get; set; }
        public System.DateTime FechaAsignacion { get; set; }
        public Nullable<System.DateTime> FechaDesasignacion { get; set; }
    
        public virtual TEstadoProcesal TEstadoProcesal { get; set; }
        public virtual TMateria TMateria { get; set; }
        public virtual TMoneda TMoneda { get; set; }
        public virtual TParticipacionEstado TParticipacionEstado { get; set; }
    }
}
