//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGR.LEX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEstadosxExpediente
    {
        public int idEstadoProcesal { get; set; }
        public string NumExpediente { get; set; }
        public System.DateTime fechaHora { get; set; }
        public string Observaciones { get; set; }
    
        public virtual TEstadoProcesal TEstadoProcesal { get; set; }
    }
}
