//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGR.LEX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class TMoneda
    {
      
        public TMoneda()
        {
            this.TDetalleExpediente = new HashSet<TDetalleExpediente>();
            this.TDetalleExpediente1 = new HashSet<TDetalleExpediente>();
        }
       [Display(Name = "ID")]
        public int idMoneda { get; set; }
        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }
    
       
        public virtual ICollection<TDetalleExpediente> TDetalleExpediente { get; set; }
      
        public virtual ICollection<TDetalleExpediente> TDetalleExpediente1 { get; set; }
    }
}
