//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGR.LEX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMovimientosxAudiencias
    {
        public int idAudiencia { get; set; }
        public int idEstado { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime Fecha { get; set; }
        public int idMovimiento { get; set; }
    
        public virtual TAudiencias TAudiencias { get; set; }
        public virtual TEstadosxAudiencia TEstadosxAudiencia { get; set; }
    }
}
