//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGR.LEX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNegociacionesxExpediente
    {
        public string NumExpediente { get; set; }
        public byte Tipo_Negociacion { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public System.DateTime Fecha_Revision { get; set; }
        public System.DateTime Fecha_Vence { get; set; }
        public string Observaciones { get; set; }
    
        public virtual TExpediente TExpediente { get; set; }
        public virtual TTiposNegociacion TTiposNegociacion { get; set; }
    }
}
