//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGR.LEX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNotificacionesxExpediente
    {
        public string idNumExpediente { get; set; }
        public int ConsecutivoNotificacion { get; set; }
        public string NumResolucion { get; set; }
        public Nullable<System.DateTime> FechaPGR { get; set; }
        public int NumCopia { get; set; }
        public int idMedioNotificacion { get; set; }
        public Nullable<int> idAnomalia { get; set; }
        public Nullable<bool> Anexos { get; set; }
        public string NumOficio { get; set; }
        public bool EntregaInmediata { get; set; }
        public string ExpedienteOriginal { get; set; }
        public string NumCarpeta { get; set; }
        public Nullable<byte> AvisadoChk { get; set; }
    
        public virtual TAnomalias TAnomalias { get; set; }
        public virtual TExpediente TExpediente { get; set; }
        public virtual TMediosNotificacion TMediosNotificacion { get; set; }
    }
}
