//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGR.LEX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNotificacioneSinExpediente
    {
        public int idAnomalia { get; set; }
        public byte Area { get; set; }
        public bool Asociado { get; set; }
        public Nullable<bool> Anexos { get; set; }
        public System.DateTime FechaPGR { get; set; }
        public Nullable<byte> InstitucionInvolucrada { get; set; }
        public Nullable<int> DespachoJudicial { get; set; }
        public int Materia { get; set; }
        public string NumOficio { get; set; }
        public string Parte { get; set; }
        public long Procurador { get; set; }
        public string Resolucion { get; set; }
        public byte idMedioNotificacion { get; set; }
        public int idTipoExpediente { get; set; }
        public int idParticipacionEstado { get; set; }
        public int idNotificacionPK { get; set; }
    
        public virtual TParticipacionEstado TParticipacionEstado { get; set; }
        public virtual TTipoExpediente TTipoExpediente { get; set; }
        public virtual TAnomalias TAnomalias { get; set; }
    }
}
