//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGR.LEX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPlanosxExpediente
    {
        public string NumExpediente { get; set; }
        public string Num_Plano { get; set; }
        public int Area_Plano { get; set; }
        public string Hoja_Cartografica { get; set; }
        public short Vertical_Inicial { get; set; }
        public short Vertical_Final { get; set; }
        public short Horizontal_Inicial { get; set; }
        public short Horizontal_Final { get; set; }
        public string Observaciones { get; set; }
    
        public virtual TExpediente TExpediente { get; set; }
    }
}
