//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGR.LEX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTerrenosxExpediente
    {
        public string NumExpediente { get; set; }
        public short Terreno_Afectado { get; set; }
        public string Observaciones { get; set; }
    
        public virtual TExpediente TExpediente { get; set; }
        public virtual TTerrenosAfectados TTerrenosAfectados { get; set; }
    }
}
