//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGR.LEX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TTipo
    {
        [Display(Name = "ID")]
        public int idTipo { get; set; }
        [Display(Name = "Materia")]
        public int MatIdMateria { get; set; }
        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }
    
        public virtual TMateria TMateria { get; set; }
    }
}
