//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGR.LEX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVotosxExpediente
    {
        public string NumExpediente { get; set; }
        public int Juzgado { get; set; }
        public string Num_Voto { get; set; }
        public System.DateTime Resolucion { get; set; }
    
        public virtual TExpediente TExpediente { get; set; }
    }
}
